# Generated by Django 3.2.9 on 2021-11-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id_mission', models.AutoField(primary_key=True, serialize=False)),
                ('date_demande', models.DateTimeField()),
                ('objet_mission', models.CharField(max_length=500)),
                ('depart_mission', models.DateField()),
                ('retour_mission', models.DateField()),
                ('lieu_mission', models.CharField(max_length=500)),
                ('statut_mission', models.CharField(max_length=100)),
                ('numero_mission', models.CharField(max_length=20)),
                ('destination_mission', models.CharField(max_length=50)),
                ('contexte_mission', models.CharField(max_length=2000)),
                ('objectifs_mission', models.CharField(max_length=2000)),
                ('frais_extra', models.CharField(max_length=20)),
                ('chg_extra', models.CharField(max_length=20)),
                ('frais_changes', models.CharField(max_length=50)),
                ('relance_mission', models.IntegerField()),
                ('relance_cible', models.CharField(max_length=50)),
                ('type_processus', models.IntegerField()),
            ],
        ),
    ]
