# Generated by Django 3.2.9 on 2021-11-20 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id_employe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_employe', models.CharField(max_length=50)),
                ('prenoms_employe', models.CharField(max_length=50)),
                ('date_naiss_employe', models.DateField()),
                ('matricule_employe', models.CharField(max_length=50)),
                ('email_employe', models.CharField(max_length=50)),
                ('tel_employe', models.CharField(max_length=50)),
                ('fonction_employe', models.CharField(max_length=100)),
                ('login_employe', models.CharField(max_length=20)),
                ('password_employe', models.CharField(max_length=50)),
                ('compte_actif', models.CharField(max_length=10)),
                ('verrou_employe', models.CharField(max_length=10)),
                ('id_createur', models.CharField(max_length=10)),
                ('date_creation', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Envoye',
            fields=[
                ('id_envoye', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=20)),
                ('regime', models.CharField(max_length=20)),
                ('billet_avion', models.CharField(max_length=20)),
                ('statut_des_justifs', models.CharField(max_length=20)),
                ('id_employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.employe')),
                ('id_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.mission')),
            ],
        ),
    ]
