# Generated by Django 3.2.9 on 2021-11-20 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0002_employe_envoye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id_pole', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pole', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='envoye',
            name='regime',
        ),
        migrations.AddField(
            model_name='mission',
            name='avion',
            field=models.CharField(choices=[('O', 'OUI'), ('N', 'NON')], default='O', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='id_demandeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='regime',
            field=models.CharField(choices=[('R', 'Réel'), ('F', 'Forfait')], default='R', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='envoye',
            name='id_mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envoye', to='quickstart.mission'),
        ),
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id_entite', models.AutoField(primary_key=True, serialize=False)),
                ('nom_entite', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=20)),
                ('id_pole_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickstart.pole')),
            ],
        ),
    ]
