# Generated by Django 3.2.9 on 2021-11-21 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0004_alter_entite_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'permissions': (('supervision', 'peut superviser'), ('approbation', 'peut faire une approbbation'), ('numero', 'peut attribuer le numero'), ('forfait', 'peut changer le forfait'), ('validation_rh', 'peut validation du drh'), ('validation_tg', 'peut validation du tg'))},
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
