# Generated by Django 3.2.9 on 2021-11-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0005_auto_20211121_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('supervision', 'peut superviser'), ('approbation', 'peut faire une approbbation'), ('numero', 'peut attribuer le numero'), ('forfait', 'peut changer le forfait'), ('validation_rh', 'peut validation du drh'), ('validation_tg', 'peut validation du tg')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={},
        ),
    ]
