# Generated by Django 3.2.9 on 2021-11-21 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0006_auto_20211121_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='id_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employe',
            name='id_createur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createur', to=settings.AUTH_USER_MODEL),
        ),
    ]
